### ISSUE TITLE
Problem in targetSdkVersion 29 and High 

### ISSUE THREAD

**Issue by Ahmedbadereldin** [pontehu/respresso-client-android#2]
I have issue when I'm using targetSdkVersion 29 and High 

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: hu.ponte.hellorespresso, PID: 2428
    java.lang.RuntimeException: Unable to start activity ComponentInfo{hu.ponte.hellorespresso/hu.ponte.hellorespresso.MainActivity}: android.view.InflateException: Binary XML file line #17 in hu.ponte.hellorespresso:layout/abc_screen_simple: Binary XML file line #17 in hu.ponte.hellorespresso:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3308)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: android.view.InflateException: Binary XML file line #17 in hu.ponte.hellorespresso:layout/abc_screen_simple: Binary XML file line #17 in hu.ponte.hellorespresso:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout
     Caused by: android.view.InflateException: Binary XML file line #17 in hu.ponte.hellorespresso:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Field.get(java.lang.Object)' on a null object reference`

**Comment by jozsefmezei** [comment]
We fixed the bug and released a snapshot version of live localization dependency. We have to test it but you can try it out as well. Please checkout to feature/androidx branch.

**Comment by Ahmedbadereldin** [comment]
Ok @jozsefmezei
